### ISSUE TITLE
Toolwindow should show path to Makefiles

### ISSUE THREAD

**Issue by kreiger** [kropp/intellij-makefile#180]
Currently my make tool window is hard to use, because it looks like this:

![image](https://user-images.githubusercontent.com/685040/89167768-1c8ec100-d57c-11ea-9f2f-b4e66d8991e5.png)

It would be nice if the tool window would show the path to the Makefiles, relative to the project root.

It would be even nicer if they were displayed as a tree, but not necessary.

**Comment by east825** [comment]
A huge +1 to this one. Even in a project with much fewer Makefiles, such as CPython sources, it's absolutely cryptic which node corresponds to the main one at the project's root (spoiler: the third one). So I'd also reorder the nodes by the relative path to the project's root, so that the root-level Makefile was always on top.

![image](https://user-images.githubusercontent.com/1007556/94987618-49f1ee00-0570-11eb-9fe6-7ef5247bb92d.png)

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
