### ISSUE TITLE
The plugin doesn't validate escaped command separator by back slash "\:" for command looks like "setup:install"

### ISSUE THREAD

**Issue by imilyukov** [kropp/intellij-makefile#72]
Hi there,
Could you add  possibility validate escaped command separator "\\:" for command name looks like Symfony style command. For example: setup\\:install or docker\\:build or the same.
For now the plugin thinks that commands with this naming are not valid.

Many Thanks

**Comment by sindre-nistad** [comment]
I have a similar issue, where escaped `#` are interpreted as a regular comment.

Thus, the rest of the `Makefile` cannot be interpreted properly. I.e. the syntax highlighting, and IntelliSense ceases to work.

**Comment by zshift** [comment]
The issue seems to be there's no support in the lexer https://github.com/kropp/intellij-makefile/blob/master/grammars/MakefileLexer.flex

I'm digging into this, as a few variables holding URLs is causing entire makefiles to become unparseable. eg, `https://site.com/page.html#anchor-on-page` requires escaping `https://site.com/page.html\#anchor-on-page`, but the grammar recognizes the anchor as the beginning of a comment.

Anyone with experience in flex or grammars, please shoot me a message.
