### ISSUE TITLE
Can't use WSL make

### ISSUE THREAD

**Issue by bmulvey1** [kropp/intellij-makefile#73]
CLion 2018.1.1
Build #CL-181.4445.84, built on April 10, 2018
JRE: 1.8.0_152-release-1136-b27 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

This might be a JetBrains issue, but if I configure the path to make as being to WSL make (Ubuntu 16.04) and try to run a Makefile, I get an error about make not being a Win32 app (not surprising in hindsight). Is there any way to build using make via SSH like with the stock behavior for CMake (
![image](https://user-images.githubusercontent.com/22732775/42299411-0618ea40-7fd9-11e8-996e-9d9de0f2c7b9.png) rather than using a Windows native version of make? Especially when the CMake toolchain already looks for make.

**Comment by RPCMoritz** [comment]
Happy birthday to this issue! I ran into a similar issue, and hope being able to expand a bit:
Pure Makefile projects based on this plugin don't appear to use the configured Toolchain at all. Instead they have a single-field "path-to-make" config value, which is used exclusively, and natively.


My current idea on how to work around that, is to create a wrapper around make, which does the ssh into WLS and runs make there. I'm pretty sure the result will be a fairly ugly bit of intransparent script magic, especially compared to the high-tech Jet-Brains-Toolchains solution. Sadly, this issue here is also the closest I've found anyone to confronting that subject, so looks like we're on our own.

Alternatively, integration of this plugin with toolchains would also be helpful.
Also paging @timeamagyar .

**Comment by kropp** [comment]
The plugin has been moved to https://github.com/JetBrains/intellij-plugins and is now bundled in CLion and GoLand.

This repository is no longer maintained, please submit all feature requests and bug reports to https://youtrack.jetbrains.com/issues/CPP
